### ISSUE TITLE
Notification email adresss

### ISSUE THREAD

**Issue by chaudj** [CodeObia/DSpace#11]
Could you please change the notification email from webmaster@knowledgearc.com? 
![image](https://user-images.githubusercontent.com/3154601/63564770-fd7c6680-c598-11e9-886f-4475b0fa38a5.png)

**Comment by mohammadsalem** [comment]
@chaudj to which email this should be changed?

**Comment by mohammadsalem** [comment]
@chaudj this issue has been resolved, please close if everything is ok.
